version: '3'

services:
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - /db_data:/var/lib/postgresql/data
    networks:
      - db_net

networks:
  db_net:
    driver: bridge
